# Generated by Django 3.0.8 on 2020-08-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_phoneotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneotp',
            old_name='phone_number',
            new_name='mobile',
        ),
    ]
